-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. Create Governorates Table
create table if not exists public.governorates (
  id bigint generated by default as identity primary key,
  name text not null
);

-- 2. Create Delegations Table
create table if not exists public.delegations (
  id bigint generated by default as identity primary key,
  name text not null,
  governorate_id bigint references public.governorates(id) on delete cascade
);

-- 3. Create Companies Table
create table if not exists public.companies (
  id uuid default uuid_generate_v4() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_id uuid references auth.users(id) not null,
  name text not null,
  manager_name text,
  matricule_fiscal text,
  email text,
  phone_number text,
  address text,
  logo_url text,
  governorate_id bigint references public.governorates(id),
  delegation_id bigint references public.delegations(id),
  is_fully_exporting boolean default false,
  is_subject_to_fodec boolean default false,
  activity text check (activity in ('commercial', 'service', 'industriel', 'extractive')),
  
  -- Add indexes for performance
  constraint companies_user_id_idx unique (id, user_id)
);

-- 4. Enable RLS
alter table public.companies enable row level security;
alter table public.governorates enable row level security;
alter table public.delegations enable row level security;

-- 5. RLS Policies
-- Companies: Users can only see and manage their own companies
create policy "Users can view their own companies"
  on public.companies for select
  using (auth.uid() = user_id);

create policy "Users can insert their own companies"
  on public.companies for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own companies"
  on public.companies for update
  using (auth.uid() = user_id);

create policy "Users can delete their own companies"
  on public.companies for delete
  using (auth.uid() = user_id);

-- Governorates/Delegations: Public read access
create policy "Public read access to governorates"
  on public.governorates for select
  using (true);

create policy "Public read access to delegations"
  on public.delegations for select
  using (true);

-- 6. Storage Bucket for Logos
insert into storage.buckets (id, name, public)
values ('company_logos', 'company_logos', true)
on conflict (id) do nothing;

-- Storage Policies
create policy "Logo Access"
  on storage.objects for select
  using ( bucket_id = 'company_logos' );

create policy "Logo Upload"
  on storage.objects for insert
  with check ( bucket_id = 'company_logos' and auth.role() = 'authenticated' );

create policy "Logo Update"
  on storage.objects for update
  using ( bucket_id = 'company_logos' and auth.role() = 'authenticated' );
